CBTD.Web/Pages/Cart/Index.cshtml.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Claims;
using CBTD.Infrastructure;
using CBTD.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CBTD.Web.Pages.Cart;

public class Index : PageModel
{
    private readonly UnitOfWork _unitOfWork;
      
    public ShoppingCartVM ShoppingCartVm { get; set; }
    public Index(UnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult OnGet()
    {
        var claimsIdentity = User.Identity as ClaimsIdentity;
        
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        
        ShoppingCartVm = new ShoppingCartVM()
        {
            cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, u => u.ProductId, "Product"),
        };
        foreach (var item in ShoppingCartVm.cartItems)
        {
            item.CartPrice = GetPriceBasedOnQuantity(item.Count, item.Product.UnitPrice,
                item.Product.HalfDozenPrice, item.Product.DozenPrice);
            ShoppingCartVm.CartTotal += (item.CartPrice * item.Count);

        }
        return Page();
        
    }
    
    public IActionResult OnPostMinus(int cartId)
    {
        var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
        if (cart.Count == 1)
        {
            _unitOfWork.ShoppingCart.Delete(cart);
        }


        else
        {
            cart.Count -= 1;


            _unitOfWork.ShoppingCart.Update(cart);
        }
        _unitOfWork.Commit();


        var cnt = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
        //HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
        return RedirectToPage();




    }


    public IActionResult OnPostPlus(int cartId)
    {
        var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
        cart.Count += 1;


        _unitOfWork.ShoppingCart.Update(cart);




        _unitOfWork.Commit();




        return RedirectToPage();




    }


    public IActionResult OnPostRemove(int cartId)
    {
        var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
        _unitOfWork.ShoppingCart.Delete(cart);
        _unitOfWork.Commit();
        var cnt = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
        //HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
        return RedirectToPage();


    }

    
    private double GetPriceBasedOnQuantity(double quantity, double unitPrice, double priceHalfDozen, double priceDozen)
    {
        if (quantity <= 5)
        {
            return unitPrice;
        }
        else
        {
            if (quantity <= 11)
            {
                return priceHalfDozen;
            }
            return priceDozen;
        }
    }
}

CBTD.Web/Pages/Cart/Summary.cshtml.cs
using System.Security.Claims;
using CBTD.DataAccess.Models;
using CBTD.Infrastructure;
using CBTD.Utility;
using CBTD.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CBTD.Web.Pages.Cart;

public class Summary : PageModel
{
    private readonly UnitOfWork _unitOfWork;
     
    [BindProperty]
    public ShoppingCartVM ShoppingCartVM { get; set; }
    public Summary(UnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
           
    }
    public IActionResult OnGet()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        ShoppingCartVM = new ShoppingCartVM()
        {
            cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                includes: "Product"),
            OrderHeader = new()
        };
        ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.Get(
            u => u.Id == claim.Value);

        ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.FullName;
        ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
        ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
        ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
        ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
        ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;

        foreach (var cart in ShoppingCartVM.cartItems)
        {
            cart.CartPrice = GetPriceBasedOnQuantity(cart.Count, cart.Product.UnitPrice,
                cart.Product.HalfDozenPrice, cart.Product.DozenPrice);
            ShoppingCartVM.OrderHeader.OrderTotal += cart.CartPrice * cart.Count;

        }
        return Page();
    }
    
    public IActionResult OnPost()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //The Order is actually the shopping cart items, so we might as well use it

            ShoppingCartVM.cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                    includes: "Product");

            ShoppingCartVM.OrderHeader.OrderDate = System.DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicationUserId = claim.Value;

            foreach (var cart in ShoppingCartVM.cartItems)
            {
                cart.CartPrice = GetPriceBasedOnQuantity(cart.Count, cart.Product.UnitPrice,
                cart.Product.HalfDozenPrice, cart.Product.DozenPrice);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.CartPrice * cart.Count;
            }

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == claim.Value);

            ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusInProcess;

            _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Commit();

            //Once the Order Header is created, we can start cycling through our Order Details

            foreach (var cart in ShoppingCartVM.cartItems)
            {
                OrderDetails orderDetail = new()
                {
                    ProductId = cart.ProductId,
                    OrderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.CartPrice,
                    Count = cart.Count
                };
                _unitOfWork.OrderDetails.Add(orderDetail);
                _unitOfWork.Commit();
            }

            //don't forget to clear the physical shopping cart entries

            _unitOfWork.ShoppingCart.Delete(ShoppingCartVM.cartItems);
            _unitOfWork.Commit();
	return Page();
}

    
    private double GetPriceBasedOnQuantity(double quantity, double unitPrice, double priceHalfDozen, double priceDozen)
    {
        if (quantity <= 5)
        {
            return unitPrice;
        }
        else
        {
            if (quantity <= 11)
            {
                return priceHalfDozen;
            }
            return priceDozen;
        }
    }

}

CBTD.Web/Pages/Cart/Index.cshtml
@page
@model CBTD.Web.Pages.Cart.Index
@{
}
<form method="post">
    <br />
    <div class="container">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0">
                <div class="row">
                    <div class="col-6  pt-2">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Shopping Cart
                    </div>
                    <div class="col-6 text-end">
                        <a asp-page="../Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                @foreach (var item in Model.ShoppingCartVm.cartItems)
                {
                    <div class="row">
                        <div class="d-none d-lg-block col-lg-1 text-center py-2">
                            <img src="@item.Product.ImageUrl" class="rounded" style="width:100%" />
                        </div>
                        <div class="col-12 col-lg-6 pt-md-3">
                            <h5><strong>@item.Product.Name</strong></h5>
                            <p><small>@Html.Raw(item.Product.Description)</small></p>
                        </div>
                        <div class="col-12  col-lg-5 text-center row">
                            <div class="col-4 text-md-right pt-4">
                                <h6>
                                    <strong>
                                       @item.CartPrice.ToString("c")
                                        $$PRICE
                                        <span class="text-muted">&nbsp;x&nbsp;</span>@item.Count
                                    </strong>
                                </h6>
                            </div>
                            <div class="col-6 col-sm-4 col-lg-6 pt-2">
                                <button type="submit" asp-page-handler="plus" asp-route-cartId="@item.Id" class="btn btn-primary"><i class="bi bi-plus-square"></i>
                                                                    </button> &nbsp;
                                                                    <button type="submit" asp-page-handler="minus" asp-route-cartId="@item.Id" class="btn btn-warning">
                                                                        <i class="bi bi-dash-square"></i>
                                                                    </button>
                                
                                                                

            
                            </div>
                            <div class="col-2 col-sm-4 col-lg-2 text-right pt-2">
                                <button type="submit" asp-page-handler="remove" asp-route-cartId="@item.Id" class="btn btn-danger">
                                <i class="bi bi-trash-fill"></i>
                            </button>
            
                            </div>
                        </div>
                    </div>
                    <hr />
                }
              

                <div class="row">
                    <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <span class="text-info"> Total (USD)</span>
                                <strong class="text-info">@Model.ShoppingCartVm.CartTotal.ToString("c")</strong>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <div class="card-footer row">
                    <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">
                        <a asp-page="summary" class="btn btn-success form-control">Summary</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

CBTD.Web/Pages/Cart/Summary.cshtml
@page
@model CBTD.Web.Pages.Cart.Summary

@{
}
<form method="post">
	<br />
	<div class="container">
		<div class="card">
			<div class="card-header bg-dark text-light ml-0">
				<div class=" row container">
					<div class="col-6">
						<i class="fa fa-shopping-cart"></i> &nbsp;
						Order Summary
					</div>
					<div class="col-6 text-end">
						<a asp-page="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="container rounded p-2">
					<div class="row">
						<div class="col-12 col-lg-6 pb-4">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Name</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.Name" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.Name" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Phone</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.PhoneNumber" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.PhoneNumber" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Street Address</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.StreetAddress" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.StreetAddress" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>City</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.City" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.City" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>State</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.State" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.State" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Postal Code</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.PostalCode" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.PostalCode" class="text-danger"></span>
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>

							<ul class="list-group mb-3">
								@{
									var total = 0.0;
								}
								@foreach (var details in Model.ShoppingCartVM.cartItems)
								{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@details.Product.Name</h6>
											<small class="text-muted">Quantity: @details.Count</small>
										</div>
										<span class="text-muted">$@((details.CartPrice * details.Count).ToString("0.00"))</span>
										@{
											total += (details.CartPrice * details.Count);
										}
									</li>
								}

								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total (USD)</small>

									<strong class="text-info">$@total.ToString("0.00")</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-12 col-md-8 pt-2">
						<p style="color:maroon; font-size:14px;">
							Estimate Arrival Date:
							@DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()
						</p>
					</div>
					<div class="col-12 col-md-4">
						<button type="submit" value="Place Order" class="btn btn-primary form-control">Place Order</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>